### ISSUE TITLE
crack-me cannot compile because "system" was not declared in the scope

### ISSUE THREAD

**Issue by nitrocode** [GeoSn0w/Reverse-Engineering-Tutorials#1]
I'm on linux and had to also include `cstdlib` to compile `crack-me` in the first tutorial

    ✗ g++ crack-me.cpp -o crack-me
    crack-me.cpp: In function ‘void secret()’:
    crack-me.cpp:17:23: error: ‘system’ was not declared in this scope
        system("uname -a\n");

Added and it compiles correctly with g++ 5.4.0

    #include <cstdlib>

Maybe my g++ version is too old.

**Comment by roussov** [comment]
hi @nitrocode 
n this case, the reported “error” is entirely expected from the C++ side.

You have the following code:
```cpp
void secret() {
    system("uname -a\n");
}
```
And the compiler reports:

error: ‘system’ was not declared in this scope

In C++, system is declared in <cstdlib> (or in C, in <stdlib.h>).
Without that include, the compiler has no declaration for the function, which leads to the error.

The fix in the code is:

```cpp
#include <cstdlib>   // or <stdlib.h>, but <cstdlib> is the recommended C++ header.

void secret() {
    std::system("uname -a\n");  // std::system is preferable for cleanliness, but calling system(...) without the namespace also works.
}
```
The fact that it compiles after adding:

```cpp
#include <cstdlib>
```
So this behavior is completely normal; it’s not really a g++ bug, even with version 5.4.0.
